trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: MyVariableGroup

jobs:
- job: deploy
  displayName: 'Build, Test, and Deploy to Azure Container App'
  steps:

    - checkout: self
      displayName: 'Checkout repository'

    - task: NodeTool@0
      inputs:
       versionSource: 'spec'
       versionSpec: '18.x'  # Use supported Node.js version
      displayName: 'Set up Node.js'
      
    - script: npm install
      displayName: 'Install dependencies'

    - script: npx browserslist@latest --update-db
      displayName: 'Update Browserslist DB'

    - script: |
        if [ -d "tests" ]; then
          npm test -- --watchAll=false
        else
          echo "Skipping tests (No test folder found)"
        fi
      displayName: 'Run tests'

    - script: |
        export CI=false
        npm run build
      displayName: 'Build React app'

    - task: AzureCLI@2
      displayName: 'Log in to Azure'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(acrName)

    - task: Docker@2
      displayName: 'Build and push container image to registry'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(acrName)/frontend'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
          $(Build.SourceBranchName)-$(Build.BuildId)

    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp update \
            --name demoapp \
            --resource-group POC \
            --image $(acrName).azurecr.io/frontend:$(Build.SourceBranchName)-$(Build.BuildId)
